[project]
name = "default"
revision = "1.0"

[profiles.default]
MCP_REGISTRY_GITHUB_CLIENT_ID = {description = "MCP_REGISTRY_GITHUB_CLIENT_ID secret", required = true}
MCP_REGISTRY_GITHUB_CLIENT_SECRET = {description = "MCP_REGISTRY_GITHUB_CLIENT_SECRET secret", required = true}
GITHUB_TOKEN = { description = "MCP_REGISTRY_GITHUB_TOKEN secret", required = true }

[profiles.development]
# Development profile inherits all secrets from default profile
